### ISSUE TITLE
테스트 배포 후 이슈 (+모바일 예외처리)

### ISSUE THREAD

**Issue by 1000peach** [test-maker-1/testmaker_ui#61]
## 리뷰
1. 전체적으로 UI, 폰트 크기 큰 느낌
2. API 호출 시 언제 loading을 호출해야할 지 기준 회의 필요

## 의견
1. 에러 페이지에서 큰 타이틀, 버튼도 성격에 맞았음 좋겠음
2. 

## 개선사항
- [x] 사진 등록 시 처음부터 삭제 누르면 에러
- [x] 사진 등록 시 아이폰에서 갤러리 선택 가능하도록
- [x] 모바일에서 Drawer 오픈 시 스크롤 이동 제한 -> 적용되는 지 봐야 함
- [ ] 모바일에서 input창 글 입력시 깜밖임
- [x] 모바일에서 footer 버튼이 띄워져있음 (border) -> 적용되는 지 봐야 함
- [x]  alert창 (SEARCH) -> 피드에서 다른페이지 갔다가 온 후 안나옴
- [x] 태그 (한글, 영어 제외한 특수문자나 이모지는 쿼리로 받으면 안됨) -> 인코딩, 백엔드에서 쿼리로 해결
- [x] padding-bottom 빠진 페이지 추가
- [x] Error 컴포넌트 header만큼 bottom 추가
- [x] TagSwiper가 BottomBtn 위에 있는 현상
- [ ] 메타태그 추가
- [ ] redux dev 설치

**Comment by 1000peach** [comment]
어제 모바일로 한번 개발서버로 띄워봤는데 그런 현상이 있었어요 좀따 보여줄게요! @rktguswjd

**Comment by rktguswjd** [comment]
1. 모바일에서 input창 글 입력시 깜밖임
2. 모바일에서 버튼이 띄워져있음 
3. alert창 -> 피드에서 다른페이지 갔다가 온 후 안나옴 
4. 태그(한글, 영어 제외한 특수문자나 이모지는 쿼리로 받으면 안됨)

**Comment by 1000peach** [comment]
이미지 퍼블릭에 넣기
